// Static movie data for Vercel serverless API
// Matches the schema expected by the frontend

const movies = [
    { _id: 'static_1', tmdbId: 634649, title: 'Spider-Man: No Way Home', genre: 'Action', releaseYear: 2021, description: 'Spider-Man seeks help from Doctor Strange to restore his secret identity.', thumbnail: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', trailerUrl: 'https://www.youtube.com/watch?v=JfVOs4VSpmA', rating: 8.2, source: 'static' },
    { _id: 'static_2', tmdbId: 299534, title: 'Avengers: Endgame', genre: 'Action', releaseYear: 2019, description: 'The Avengers assemble once more to reverse Thanos snap.', thumbnail: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg', trailerUrl: 'https://www.youtube.com/watch?v=TcMBFSGVi1c', rating: 8.4, source: 'static' },
    { _id: 'static_3', tmdbId: 414906, title: 'The Batman', genre: 'Action', releaseYear: 2022, description: 'Batman ventures into Gotham City underworld.', thumbnail: 'https://image.tmdb.org/t/p/w500/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg', trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4', rating: 7.8, source: 'static' },
    { _id: 'static_4', tmdbId: 361743, title: 'Top Gun: Maverick', genre: 'Action', releaseYear: 2022, description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator.', thumbnail: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', trailerUrl: 'https://www.youtube.com/watch?v=qSqVVswa420', rating: 8.3, source: 'static' },
    { _id: 'static_5', tmdbId: 76600, title: 'Avatar: The Way of Water', genre: 'Adventure', releaseYear: 2022, description: 'Jake Sully lives with his newfound family formed on the planet of Pandora.', thumbnail: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', trailerUrl: 'https://www.youtube.com/watch?v=d9MyW72ELq0', rating: 7.6, source: 'static' },
    { _id: 'static_6', tmdbId: 507086, title: 'Jurassic World Dominion', genre: 'Adventure', releaseYear: 2022, description: 'Four years after the destruction of Isla Nublar, dinosaurs now live alongside humans.', thumbnail: 'https://image.tmdb.org/t/p/w500/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg', trailerUrl: 'https://www.youtube.com/watch?v=fb5ELWi-ekk', rating: 7.0, source: 'static' },
    { _id: 'static_7', tmdbId: 438148, title: 'Minions: The Rise of Gru', genre: 'Animation', releaseYear: 2022, description: 'The untold story of one twelve-year-old\'s dream to become the world\'s greatest supervillain.', thumbnail: 'https://image.tmdb.org/t/p/w500/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg', trailerUrl: 'https://www.youtube.com/watch?v=ZIGlqId_x5A', rating: 7.5, source: 'static' },
    { _id: 'static_8', tmdbId: 718789, title: 'Lightyear', genre: 'Animation', releaseYear: 2022, description: 'The story of Buzz Lightyear and his adventures to infinity and beyond.', thumbnail: 'https://image.tmdb.org/t/p/w500/ox4goZd956BxqJH6iLwhWPL9ct4.jpg', trailerUrl: 'https://www.youtube.com/watch?v=BwPL0Md_QFQ', rating: 7.1, source: 'static' },
    { _id: 'static_9', tmdbId: 675353, title: 'Sonic the Hedgehog 2', genre: 'Family', releaseYear: 2022, description: 'When the manic Dr. Robotnik returns with a new partner, Knuckles, Sonic and his new friend Tails is all that stands in their way.', thumbnail: 'https://image.tmdb.org/t/p/w500/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', trailerUrl: 'https://www.youtube.com/watch?v=G5kzUpWAusI', rating: 7.5, source: 'static' },
    { _id: 'static_10', tmdbId: 505642, title: 'Black Panther: Wakanda Forever', genre: 'Drama', releaseYear: 2022, description: 'The people of Wakanda fight to protect their home from intervening world powers.', thumbnail: 'https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg', trailerUrl: 'https://www.youtube.com/watch?v=_Z3QKkl1WyM', rating: 7.3, source: 'static' },
    { _id: 'static_11', tmdbId: 453395, title: 'Doctor Strange in the Multiverse of Madness', genre: 'Fantasy', releaseYear: 2022, description: 'Doctor Strange teams up with a mysterious teenage girl who can travel across multiverses.', thumbnail: 'https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', trailerUrl: 'https://www.youtube.com/watch?v=aWzlQ2N6qqg', rating: 7.0, source: 'static' },
    { _id: 'static_12', tmdbId: 616037, title: 'Thor: Love and Thunder', genre: 'Comedy', releaseYear: 2022, description: 'Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher.', thumbnail: 'https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg', trailerUrl: 'https://www.youtube.com/watch?v=Go8nTmfrQd8', rating: 6.8, source: 'static' },
    { _id: 'static_13', tmdbId: 109445, title: 'Frozen', genre: 'Animation', releaseYear: 2013, description: 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice.', thumbnail: 'https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg', trailerUrl: 'https://www.youtube.com/watch?v=TbQm5doF_Uc', rating: 7.4, source: 'static' },
    { _id: 'static_14', tmdbId: 354912, title: 'Coco', genre: 'Animation', releaseYear: 2017, description: 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather.', thumbnail: 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg', trailerUrl: 'https://www.youtube.com/watch?v=Ga6RYejo6Hk', rating: 8.4, source: 'static' },
    { _id: 'static_15', tmdbId: 597, title: 'Titanic', genre: 'Drama', releaseYear: 1997, description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', thumbnail: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', trailerUrl: 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ', rating: 7.9, source: 'static' },
    { _id: 'static_16', tmdbId: 475557, title: 'Joker', genre: 'Drama', releaseYear: 2019, description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.', thumbnail: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', trailerUrl: 'https://www.youtube.com/watch?v=zAGVQLHvwOY', rating: 8.2, source: 'static' },
    { _id: 'static_17', tmdbId: 420818, title: 'The Lion King', genre: 'Family', releaseYear: 2019, description: 'After the murder of his father, a young lion prince flees his kingdom.', thumbnail: 'https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg', trailerUrl: 'https://www.youtube.com/watch?v=7TavVZMewpY', rating: 6.8, source: 'static' },
    { _id: 'static_18', tmdbId: 155, title: 'The Dark Knight', genre: 'Crime', releaseYear: 2008, description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham.', thumbnail: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY', rating: 9.0, source: 'static' },
    { _id: 'static_19', tmdbId: 27205, title: 'Inception', genre: 'Science Fiction', releaseYear: 2010, description: 'A thief who steals corporate secrets through dream-sharing technology.', thumbnail: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0', rating: 8.8, source: 'static' },
    { _id: 'static_20', tmdbId: 274, title: 'The Shawshank Redemption', genre: 'Drama', releaseYear: 1994, description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption.', thumbnail: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', trailerUrl: 'https://www.youtube.com/watch?v=6hB3S9bIaco', rating: 9.3, source: 'static' }
];

module.exports = movies;
